name: Deploy MkDocs to gh-pages branch

on:
  push:
    branches: [ "master" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing to gh-pages branch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Build and Deploy to gh-pages
        run: |
          mkdocs build
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r site/* .
          rm -rf site
          git add .
          git commit -m "Deploy MkDocs site from ${{ github.sha }}"
          git push origin gh-pages --force
